services:
  - type: web
    name: NeuraAI_v10k_Hyperluxe
    env: python
    region: frankfurt  # you can change to oregon, singapore, etc.
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn main:app --workers=2 --threads=4 --timeout=120
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: neura_ai_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000

databases:
  - name: neura_ai_db
    plan: free